### ISSUE TITLE
Ошибка со скинами новых версий

### ISSUE THREAD

**Issue by YouTy6bl4** [NC22/Minecraft-HD-skin-viewer-2D#2]
Начиная с 1.8 скины стали размером в 64x64. Если вывести его через скрипт, то скрипт просто не сможет его отобразить.

**Comment by NC22** [comment]
Спасибо за инфу. Уже давно не слежу за темой. Посмотрел новый формат, обновил вывод, вроде бы все впорядке

**Comment by YouTy6bl4** [comment]
Ага, спасибо:)
