### ISSUE TITLE
Пара идей

### ISSUE THREAD

**Issue by YouTy6bl4** [NC22/Minecraft-HD-skin-viewer-2D#3]
Предлагаю в гет запрос добавить значение name, если мы туда укажем ник то... И при пустом значении отображать дефолтный скин. Заметил в скрипте так же проверку на hd и стандартный плащ и скин, только не понял его смысла. Может лучше стоит это убрать?
P.s. именно в этом скрипте https://github.com/NC22/Minecraft-HD-skin-viewer-2D/blob/master/selftest/skinTest.php

**Comment by NC22** [comment]
Да, думаю для наглядности не помешает добавить проверки на валидность скина в тестовый скрипт, скорректировать название переменных. Но на всякий случай так же добавлю предупреждение если это не очевидно. Этот скрипт является юниттестом и содержит некоторые из возможных сценариев использования, просто чтобы убедится, что вывод образов в разных разрешениях \ с плащем \ без проходит корректно. Не рекомендуется использовать его в качестве готового решения т.к. да в нем нет валидации гет запросов \ проверки на существование файла и последующей реакции на это. 

get-параметр mode = hd здесь выступает просто названием файла

Практическое же применение класса зависит от конкретной задачи. 
Так ниже представлен пример использования в классе пользователя в системе управления, где скин по умолчанию зависит еще так же и от пола.

https://github.com/NC22/webMCR/blob/master/upload/instruments/user.class.php#L767
https://github.com/NC22/webMCR/blob/master/upload/instruments/user.class.php#L525

**Comment by YouTy6bl4** [comment]
Ну мало ли есть те кто используют его в продакшене)

**Comment by YouTy6bl4** [comment]
А вот и бажек. Не отображается грудина у скинов 64x64
http://prntscr.com/d3fdm2

**Comment by NC22** [comment]
Ок. Спасибо. Вроде бы поправил. 
Еще заметил, что с версии 1.8 появилась "фишка" с тонкими руками. Внес соответствующие изменения. 
Единственное смутило, что в шаблоне описывающем скин с тонкими руками (http://minecraft.gamepedia.com/File:1.8_slim_arms.png) выделяемое пространство под фронтальную часть руки (3 пикселя в ширину) не совпадает с пространством выделяемым для обратной стороны (4 пикселя в ширину) . Проверил вывод некоторых таких образов с тонкими руками; на первый взгляд корректно, но возможно есть какие-то исключения.

**Comment by NC22** [comment]
И кидай сразу если что некорректные скины для примера, чтобы было оперативней. 
актуальное мыло здесь 
http://www.catface.ru/statics/feedback

**Comment by YouTy6bl4** [comment]
Предлагаю добавить проверку на скин и плащ. У меня на проекте проверка идёт через размер, но бывает всё равно не спасает.

**Comment by NC22** [comment]
Есть уже методы.

SkinViewer2D::isValidCloak($way_cloak); (https://github.com/NC22/Minecraft-HD-skin-viewer-2D/blob/master/SkinViewer2D.class.php#L366)
SkinViewer2D::isValidSkin($way_skin); (https://github.com/NC22/Minecraft-HD-skin-viewer-2D/blob/master/SkinViewer2D.class.php#L338)

Методы простенькие, но их вполне достаточно. Включают проверку на то, что файл является изображением + проверка допустимого соотношения сторон.

Допустимые соотношения сторон см. самом начале класса, это SkinViewer2D::$skinProps и SkinViewer2D::$cloakProps их допустимо переопределять \ убирать ненужное.

Постфактум проверяем результат выполнения SkinViewer2D::createPreview($way_skin, $way_cloak, $side, $size)

Эта функция работает только с валидными png изображениями и вернет false в случае некоректного изображения.

В конце концов принятый файл для надежности всегда можно пересохранить к примеру так
 $skin = imagecreatefrompng($way_skin); imagepng($skin, $way_skin); 
чтобы исключить возможность встраивания в файл троянов \ мусора

А так да, предварительно можно проверить и размер файла.

**Comment by YouTy6bl4** [comment]
Тогда странно, что при загрузке hd плаща как скина скрипт его показывает. Проверял даже на тестовом скрипте.

**Comment by NC22** [comment]
По пропорциям и образ и плащ по логике не должны быть идентичны. По умолчанию в скрипте считаются валидными образы как 64х64 так и 64х32, плащи 64х32 и 22x17. Не в курсе какие соотношения сторон актуальны для нынешних версий майнкрафта, так что включил все возможные, какие попадались при работе с прошлыми версиями и сейчас.  Так что нужно убрать лишние если нужно их различать между собой.

Если по пропорциям и плащи и образы все таки могут быть одинаковы то тогда да наверное можно какую нибудь зону контрольных пикселей взять чтобы одно в другой слот было нельзя поместить, но это уже не совсем вопрос безопасности, а дополнительные фишки.

**Comment by YouTy6bl4** [comment]
Хм, может тогда игроков принудительно заставить ставить себе скины с соотношением 64x64? Только такой вариант может помочь.

**Comment by NC22** [comment]
Если принципиально отличать плащи от скинов то да, пока так. Если бы мне очень нужно было реализовать что то такое то из простых способов например нужно на скине проверить несколько точек на прозрачность. К примеру так как здесь проверяется "худая" рука или "толстая" 
https://github.com/NC22/Minecraft-HD-skin-viewer-2D/blob/master/SkinViewer2D.class.php#L98

Если например на месте грудины ничего нет - значит это изображение плаща к примеру. Можно усложнить и проверять несколько строк пикселей в цикле что они ничем не заняты и что это не просто случайная точка оказалась пустой.  Как будет время посмотрю.
